# List benchmark
{{$namespaceNumber := DefaultParam .CL2_LIST_NAMESPACE_NUMBER 4}}
{{$configMapBytes := DefaultParam .CL2_LIST_CONFIG_MAP_BYTES 10000}}
{{$configMapGroup := DefaultParam .CL2_LIST_CONFIG_MAP_GROUP "list-configmap"}}
{{$configMapNumber := DefaultParam .CL2_LIST_CONFIG_MAP_NUMBER 3000}}
{{$secretBytes := DefaultParam .CL2_LIST_SECRET_BYTES 10000}}
{{$secretGroup := DefaultParam .CL2_LIST_SECRET_GROUP "list-secret"}}
{{$secretNumber := DefaultParam .CL2_LIST_SECRET_NUMBER 3000}}

{{$listReplicas := DefaultParam .CL2_LIST_BENCHMARK_PODS 1}}
{{$inflight := DefaultParam .CL2_LIST_CONCURRENCY 2}}
{{$qps := DefaultParam .CL2_LIST_QPS -1}}

{{$namespacedPodCpu := DefaultParam .CL2_LIST_BENCHMARK_POD_CPU "400m"}}
{{$namespacedPodMemory := DefaultParam .CL2_LIST_BENCHMARK_POD_MEMORY "800Mi"}}
{{$clusterScopedPodCpu := DefaultParam .CL2_LIST_BENCHMARK_POD_CPU "2000m"}}
{{$clusterScopedPodMemory := DefaultParam .CL2_LIST_BENCHMARK_POD_MEMORY "4000Mi"}}

name: List benchmark
namespace:
  number: {{$namespaceNumber}}
tuningSets:
- name: Sequence
  parallelismLimitedLoad:
    parallelismLimit: 10
steps:
- name: Setup namespace for list benchmark pods
  phases:
  - replicasPerNamespace: 1
    tuningSet: Sequence
    objectBundle:
    - basename: list-benchmark
      objectTemplatePath: namespace.yaml
- name: Setup permissions
  phases:
  - replicasPerNamespace: 1
    tuningSet: Sequence
    objectBundle:
    - basename: list-clusterrole
      objectTemplatePath: clusterrole.yaml
  - replicasPerNamespace: 1
    tuningSet: Sequence
    objectBundle:
    - basename: list-clusterrolebinding
      objectTemplatePath: clusterrolebinding.yaml
  - namespaceRange:
      min: 1
      max: {{$namespaceNumber}}
    replicasPerNamespace: 1
    tuningSet: Sequence
    objectBundle:
    - basename: list-rolebinding
      objectTemplatePath: rolebinding.yaml

- name: Create configmaps
  phases:
  - namespaceRange:
      min: 1
      max: {{$namespaceNumber}}
    tuningSet: Sequence
    replicasPerNamespace: {{$configMapNumber}}
    objectBundle:
    - basename: {{$configMapGroup}}
      objectTemplatePath: configmap.yaml
      templateFillMap:
        bytes: {{$configMapBytes}}
        group: {{$configMapGroup}}
- name: Create secrets
  phases:
  - namespaceRange:
      min: 1
      max: {{$namespaceNumber}}
    tuningSet: Sequence
    replicasPerNamespace: {{$secretNumber}}
    objectBundle:
    - basename: {{$secretGroup}}
      objectTemplatePath: secret.yaml
      templateFillMap:
        bytes: {{$secretBytes}}
        group: {{$secretGroup}}

- name: "Starting measurement - list benchmark"
  measurements:
  - Identifier: APIResponsivenessPrometheusSimple
    Method: APIResponsivenessPrometheus
    Params:
      action: start
      enableViolations: false

- module:
    path: modules/list-benchmark-deployment.yaml
    params:
      namePrefix: "list-namespaced-configmaps-"
      replicas: {{$listReplicas}}
      inflight: {{$inflight}}
      uri: /api/v1/namespaces/%namespace%/configmaps
      qps: {{$qps}}
      cpu: {{$namespacedPodCpu}}
      memory: {{$namespacedPodMemory}}
      namespaced: true
      namespaceNumber: {{$namespaceNumber}}
- module:
    path: modules/list-benchmark-deployment.yaml
    params:
      namePrefix: "list-cluster-scoped-configmaps-"
      replicas: {{$listReplicas}}
      inflight: {{$inflight}}
      uri: /api/v1/configmaps
      qps: {{$qps}}
      cpu: {{$clusterScopedPodCpu}}
      memory: {{$clusterScopedPodMemory}}
      namespaced: false
- name: Wait 5 minutes
  measurements:
    - Identifier: Wait
      Method: Sleep
      Params:
        duration: 5m
- module:
    path: modules/list-benchmark-deployment.yaml
    params:
      namePrefix: "list-namespaced-configmaps-"
      namespaced: true
      namespaceNumber: {{$namespaceNumber}}
      replicas: 0
- module:
    path: modules/list-benchmark-deployment.yaml
    params:
      namePrefix: "list-cluster-scoped-configmaps-"
      replicas: 0

- module:
    path: modules/list-benchmark-deployment.yaml
    params:
      namePrefix: "list-namespaced-secrets-"
      replicas: {{$listReplicas}}
      inflight: {{$inflight}}
      uri: /api/v1/namespaces/%namespace%/secrets
      qps: {{$qps}}
      cpu: {{$namespacedPodCpu}}
      memory: {{$namespacedPodMemory}}
      namespaced: true
      namespaceNumber: {{$namespaceNumber}}
- module:
    path: modules/list-benchmark-deployment.yaml
    params:
      namePrefix: "list-cluster-scoped-secrets-"
      replicas: {{$listReplicas}}
      inflight: {{$inflight}}
      uri: /api/v1/secrets
      qps: {{$qps}}
      cpu: {{$clusterScopedPodCpu}}
      memory: {{$clusterScopedPodMemory}}
      namespaced: false
- name: Wait 5 minutes
  measurements:
    - Identifier: Wait
      Method: Sleep
      Params:
        duration: 5m
- module:
    path: modules/list-benchmark-deployment.yaml
    params:
      namePrefix: "list-namespaced-secrets-"
      namespaced: true
      namespaceNumber: {{$namespaceNumber}}
      replicas: 0
- module:
    path: modules/list-benchmark-deployment.yaml
    params:
      namePrefix: "list-cluster-scoped-secrets-"
      replicas: 0

- name: deleting namespace for list benchmark pods
  phases:
  - replicasPerNamespace: 0
    tuningSet: Sequence
    objectBundle:
    - basename: list-benchmark
      objectTemplatePath: namespace.yaml

- name: "Gathering measurement - list benchmark"
  measurements:
  - Identifier: APIResponsivenessPrometheusSimple
    Method: APIResponsivenessPrometheus
    Params:
      action: gather
      enableViolations: false
      useSimpleLatencyQuery: true
