# This service points to the Kubemark ApiServer, which runs on separate VM, outside of the main
# cluster.The service is needed for Prometheus (discovery and monitoring in Prometheus server is
# based on k8s services and endpoints) in order to collect metrics from the Kubemark ApiServer.
apiVersion: v1
kind: Service
metadata:
  namespace: kubemark
  name: kubemark-master
  labels:
    instance: kubemark-master
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: apiserver
      port: 443
    - name: kubelet
      port: 10250
    - name: kube-scheduler
      port: 10251
    - name: kube-controller-manager
      port: 10252
