version: 2
updates:
- package-ecosystem: docker
  directory: /util-images/network/netperfbenchmark
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: docker
  directory: /network/tools/network-policy-enforcement-latency/policy-creation-enforcement-latency
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: docker
  directory: /util-images/request-benchmark
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: docker
  directory: /util-images/access-tokens
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: docker
  directory: /util-images/probes
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: docker
  directory: /util-images/scratch
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: docker
  directory: /network/tools/network-policy-enforcement-latency/pod-creation-reachability-latency
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: docker
  directory: /util-images/watch-list
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: docker
  directory: /dns/dnsperfgo
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: docker
  directory: /dns/dnsperfgo/vendor/golang.org/x/net/http2
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: docker
  directory: /dns/image
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: docker
  directory: /perfdash
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: docker
  directory: /slo-monitor
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: docker
  directory: /util-images/sleep
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: docker
  directory: /util-images/containerd
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: docker
  directory: /network/benchmarks/netperf
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: gomod
  directory: /util-images/network/netperfbenchmark
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: gomod
  directory: /util-images/access-tokens
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: gomod
  directory: /util-images/request-benchmark
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: gomod
  directory: /util-images/probes
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: gomod
  directory: /dns/jsonify
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: gomod
  directory: /clusterloader2
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: gomod
  directory: /dns/dnsperfgo
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: gomod
  directory: /util-images/watch-list
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: gomod
  directory: /perfdash
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: gomod
  directory: /network/tools/network-policy-enforcement-latency
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: gomod
  directory: /benchmark
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: gomod
  directory: /slo-monitor
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
- package-ecosystem: gomod
  directory: /network/benchmarks/netperf
  schedule:
    interval: weekly
  labels:
    - "ok-to-test"
    - "kind/cleanup"
