{{$SetServiceProxyLabel := DefaultParam .SetServiceProxyLabel false}}

apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
{{if and $SetServiceProxyLabel (IsEven .Index)}}
  labels:
    service.kubernetes.io/service-proxy-name: foo
{{end}}
spec:
  selector:
    svc: {{.Name}}
  ports:
  - port: 80
    targetPort: 80
