run:
  timeout: 5m

linters-settings:
  golint:
    min-confidence: 0
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - gofmt
    - golint
    - errcheck
    # TODO(oxddr): enable more checkers
    # - deadcode
    # - misspell

service:
  golangci-lint-version: 1.23.x # use the fixed version to not introduce new linters unexpectedly
  prepare:
    - echo "here I can run custom commands, but no preparation needed for this repo"
