# Endpoints object for the kubelet running on master node.
apiVersion: v1
kind: Endpoints
metadata:
  namespace: kube-system
  name: master
  labels:
    k8s-app: master
subsets:
  - addresses:
      - ip: {{.MasterIp}}
    ports:
      - name: etcd
        port: 2379
      - name: kubelet
        port: 10250
