{{$volumeType := .VolumeType}}
{{$index := .Index}}
{{$appName := .AppName}}
{{$volumesPerPod := .VolumesPerPod}}
apiVersion: v1
kind: Pod
metadata:
  name: {{.Name}}
  labels:
    app: {{.Name}}
    group: {{.Group}}
spec:
  containers:
  - name: {{.Name}}
    image: k8s.gcr.io/pause:3.1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
      name: {{.Name}}
    volumeMounts:
    {{ range $volumeIndex, $vol := Seq .VolumesPerPod }}
    - name: vol-{{$volumeIndex}}
      mountPath: /usr/share/{{$volumeIndex}}
    {{ end }}
  volumes:
  {{ range $volumeIndex, $vol := Seq .VolumesPerPod }}
  - name: vol-{{$volumeIndex}}
  {{ if eq $volumeType  "ConfigMap" }}
    configMap:
      name: vol-{{$appName}}-{{AddInt $volumeIndex (MultiplyInt $index $volumesPerPod)}}
  {{ end }}
  {{ if eq $volumeType  "EmptyDir" }}
    emptyDir: {}
  {{ end }}
  {{ if eq $volumeType  "Secret" }}
    secret:
      secretName: vol-{{$appName}}-{{AddInt $volumeIndex (MultiplyInt $index $volumesPerPod)}}
  {{ end }}
  {{ if eq $volumeType  "DownwardAPI" }}
    downwardAPI:
      items:
      - path: "pod_name"
        fieldRef:
          fieldPath: metadata.name
      - path: "pod_namespace"
        fieldRef:
          fieldPath: metadata.namespace
  {{ end }}
  {{ end }}