{{$index := .Index}}
{{$appName := .AppName}}
{{$volumesPerPod := .VolumesPerPod}}
apiVersion: v1
kind: Pod
metadata:
  name: {{.Name}}
  labels:
    app: {{.Name}}
    group: {{.Group}}
spec:
  containers:
  - name: {{.Name}}
    image: k8s.gcr.io/pause:3.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
    {{ range $volumeIndex, $vol := Seq .VolumesPerPod }}
    - name: vol-{{$volumeIndex}}
      mountPath: /usr/share/{{$volumeIndex}}
    {{ end }}
  volumes:
  {{ range $volumeIndex, $vol := Seq .VolumesPerPod }}
  - name: vol-{{$volumeIndex}}
    downwardAPI:
      items:
      - path: "pod_name"
        fieldRef:
          fieldPath: metadata.name
      - path: "pod_namespace"
        fieldRef:
          fieldPath: metadata.namespace
  {{ end }}
