# ASSUMPTIONS:
# - Underlying cluster should have 100+ nodes.
# - Number of nodes should be divisible by NODES_PER_NAMESPACE (default 100).

#Constants
# TODO(mucahitkurt) copied from load tests, open for discussion.
{{$NODE_MODE := DefaultParam .NODE_MODE "allnodes"}}
{{$NODES_PER_NAMESPACE := DefaultParam .NODES_PER_NAMESPACE 100}}
{{$PODS_PER_NODE := DefaultParam .PODS_PER_NODE 30}}

{{$POD_TEMPLATE_PATH := DefaultParam .POD_TEMPLATE_PATH "../emptydir/pod_with_emptydir.yaml"}}
{{$LOAD_TEST_THROUGHPUT := DefaultParam .LOAD_TEST_THROUGHPUT 10}}

{{$VOLUMES_PER_POD := DefaultParam .VOLUMES_PER_POD 1}}
{{$VOLUME_TEMPLATE_PATH := .VOLUME_TEMPLATE_PATH}}
{{$PROVISION_VOLUME := DefaultParam .PROVISION_VOLUME false}}

{{$APP_NAME := "pod-load"}}
{{$GROUP := "pod-with-ephemeral-volume-startup-latency"}}

#Variables
# used stateless pod SLO for initial run
{{$namespaces := DivideInt .Nodes $NODES_PER_NAMESPACE}}
{{$podStartupTimeout := 5}}
{{$totalPods := MultiplyInt $namespaces $NODES_PER_NAMESPACE $PODS_PER_NODE}}
{{$podsPerNamespace := MultiplyInt $NODES_PER_NAMESPACE $PODS_PER_NODE}}
{{$volumesPerNamespace := MultiplyInt $podsPerNamespace $VOLUMES_PER_POD}}

name: pod-with-ephemeral-volume-startup-latency
automanagedNamespaces: {{$namespaces}}
tuningSets:
- name: UniformQPS
  qpsLoad:
    qps: {{$LOAD_TEST_THROUGHPUT}}
steps:
# Start measurements
- measurements:
  - Identifier: APIResponsiveness
    Method: APIResponsiveness
    Params:
      action: reset
  - Identifier: PodWithMultiVolumeStartupLatency
    Method: PodStartupLatency
    Params:
      action: start
      labelSelector: group = {{$GROUP}}
      threshold: {{$podStartupTimeout}}s
{{ if $PROVISION_VOLUME }}
# Provision volumes
- phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: {{$volumesPerNamespace}}
    tuningSet: UniformQPS
    objectBundle:
    - basename: vol-{{$APP_NAME}}
      objectTemplatePath: {{$VOLUME_TEMPLATE_PATH}}
{{ end }}
# Create pods
- phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: {{$podsPerNamespace}}
    tuningSet: UniformQPS
    objectBundle:
    - basename: {{$APP_NAME}}
      objectTemplatePath: {{$POD_TEMPLATE_PATH}}
      templateFillMap:
        Group: {{$GROUP}}
        VolumesPerPod: {{$VOLUMES_PER_POD}}
        AppName: {{$APP_NAME}}
- measurements:
  - Identifier: WaitForRunningPodsWithStorage
    Method: WaitForRunningPods
    Params:
      desiredPodCount: {{$totalPods}}
      labelSelector: group = {{$GROUP}}
      # TODO(mucahitkurt) decide this after test roll-out phase
      timeout: 15m
# Delete pods
- phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: 0
    tuningSet: UniformQPS
    objectBundle:
    - basename: {{$APP_NAME}}
      objectTemplatePath: {{$POD_TEMPLATE_PATH}}
# Collect measurements
- measurements:
  - Identifier: PodWithMultiVolumeStartupLatency
    Method: PodStartupLatency
    Params:
      action: gather
  - Identifier: APIResponsiveness
    Method: APIResponsiveness
    Params:
      action: gather
