apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Name}}
  labels:
    app: {{.Name}}
    group: {{.Group}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.VolSize}}
