apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-critical-pods
  namespace: monitoring
spec:
  hard:
    pods: "100"
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - system-node-critical
