apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfdash
  labels:
    app: perfdash
spec:
  selector:
    matchLabels:
      app: perfdash
  template:
    metadata:
      labels:
        app: perfdash
    spec:
      containers:
      - name: perfdash
        # Version 2.33 consumes > 32GiB of memory.
        # TODO: Introduce 2.34 version which conditionally disables functionality added in 2.32 and disable it in this perf-dash instance.
        image: gcr.io/k8s-testimages/perfdash:2.32
        command:
          - /perfdash
          -   --www=true
          -   --dir=/www
          -   --address=0.0.0.0:8080
          -   --builds=100
          -   --githubConfigDir=https://api.github.com/repos/kubernetes/test-infra/contents/config/jobs/kubernetes/sig-scalability
          -   --githubConfigDir=https://api.github.com/repos/kubernetes/test-infra/contents/config/jobs/kubernetes/sig-release/release-branch-jobs
        imagePullPolicy: Always
        ports:
        - name: status
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 1
        resources:
          requests:
            cpu: "3"
            memory: 10Gi
          limits:
            cpu: "3"
            memory: 10Gi
      restartPolicy: Always
